tmp_dir_root: /panfs/panfs1.ucsd.edu/panscratch/jgsanders 
params:
  db_dir: ~/git_sw/snarkmark/test_data/test_dbs
  abundance_samples:
  assemblers:
  - megahit
  - metaspades
  binning_samples:
  mapping_assembler:
  - metaspades
  filter_db: bowtie2/phix
  trimmer: atropos
  anvio:
    centrifuge_base: /home/jgsanders/miniconda/envs/anvio2/centrifuge
    centrifuge_models: /home/jgsanders/miniconda/envs/anvio2/centrifuge/b+h+v/b+h+v
  atropos: ' -a GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A GATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGT
    -q 15 --minimum-length 100 --pair-filter any'
  humann2:
    aa_db: uniref50_mini
    nt_db: chocophlan_test
    other: ''
  maxbin: -plotmarker
  metaphlan2:
    db: mp2_mini/mp2_mini
    # taxon name to TaxID dictionary
    name2tid: 
    levels: phylum,genus,species
    map: no
  kraken:
    db: genome/rep82/kraken
    # Bracken kmer distribution file
    kmers: genome/rep82/bracken/75mers_distr.txt
    # taxonomic ranks (kingdom to species) to reestimate abundance using Bracken
    levels: phylum,genus,species
    # whether to keep original mapping file
    map: no
  centrifuge:
    db: genome/rep82/centrifuge/rep82
    # taxonomic ranks (kingdom to species) to reestimate abundance using Bracken
    levels: phylum,genus,species
    # whether to keep original mapping file
    map: yes
  bracken:
    kmers: genome/rep82/bracken/75mers_distr.txt
  shogun:
    db: genome/rep82/shogun
    # alignment algorithm: bowtie2, burst and utree
    aligner: utree
    # taxonomic ranks (kingdom to strain) to redistribute reads
    levels: phylum,genus,species
    # whether to keep original mapping file
    map: no
  mash:
    sketch_size: 1000
    kmer: 21
    min_obs: 2
  sourmash:
    scaled: 10000
    kmer: 31
samples:
  sample_S22205:
    forward: test_data/test_reads/S22205_S104_L001_R1_001.fastq.gz
    reverse: test_data/test_reads/S22205_S104_L001_R2_001.fastq.gz
  sample_S22282:
    forward: test_data/test_reads/S22282_S102_L001_R1_001.fastq.gz
    reverse: test_data/test_reads/S22282_S102_L001_R2_001.fastq.gz
